# Generated by Django 5.0.2 on 2024-02-22 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
